"""empty message

Revision ID: 7593709ef851
Revises: 
Create Date: 2018-07-29 22:34:42.524866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7593709ef851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('build_index', sa.BigInteger(), nullable=False),
    sa.Column('config_file', sa.TEXT(), nullable=False),
    sa.Column('createDatetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updateDatetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pipeline',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gitUrl', sa.String(length=255), nullable=False),
    sa.Column('ciCfgPath', sa.String(length=255), nullable=False),
    sa.Column('createDatetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updateDatetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline')
    op.drop_table('build')
    # ### end Alembic commands ###
