"""empty message

Revision ID: ebf718515bd0
Revises: 
Create Date: 2018-07-27 14:06:01.510342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebf718515bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gitUrl', sa.String(length=255), nullable=False),
    sa.Column('ciCfgPath', sa.String(length=255), nullable=False),
    sa.Column('createDatetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updateDatetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline')
    # ### end Alembic commands ###
